### ISSUE TITLE
R22/4k alternative

### ISSUE THREAD

**Issue by sepal** [prajwal1121/Portable-Synth#2]
Hi, thx for this awesome project!!
I'm wanna build one this synths myself, and I already got almost all components. The only trouble I have is with R22, the 4k ohm resistor. On digikey the resistor has currently lead time of 4 months and also other sites like mouser don't have any available.
Would a 4,02k Ohm resistor like this one also work? https://www.digikey.at/product-detail/de/yageo/RT0805BRD074K02L/YAG4909CT-ND/6617065
Sorry if this is a stupid question, but I can not tell what R22 is used for 🙈

**Comment by prajwal1121** [comment]
Cool! I'm excited to hear you're building it!

Yep, 4.02K will work perfectly fine. And no worries, its not a stupid question haha- R22(4k) and R25(10k) together make up a voltage divider through which the Teensy can monitor the battery voltage, so that small of a change in one of the resistor values won't make a difference.

**Comment by sepal** [comment]
awesome, thx for the quick reply!
